--BEGIN
--   EXECUTE IMMEDIATE 'DROP TABLE ' || 'USUARIO_CARGO';
--EXCEPTION
--   WHEN OTHERS THEN
--      IF SQLCODE != -942 THEN
--         RAISE;
--      END IF;
--END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'CARGO';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
--
--BEGIN
--   EXECUTE IMMEDIATE 'DROP TABLE ' || 'USUARIO';
--EXCEPTION
--   WHEN OTHERS THEN
--      IF SQLCODE != -942 THEN
--         RAISE;
--      END IF;
--END;

--BEGIN
--  EXECUTE IMMEDIATE 'DROP SEQUENCE ' || 'seq_usuario';
--EXCEPTION
--  WHEN OTHERS THEN
--    IF SQLCODE != -2289 THEN
--      RAISE;
--    END IF;
--END;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ' || 'seq_cargo';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;

--CREATE TABLE USUARIO(
--    ID_USUARIO NUMBER NOT NULL,
--    LOGIN varchar2(512) UNIQUE NOT NULL,
--    SENHA varchar2(512) NOT NULL,
--    PRIMARY KEY(ID_USUARIO)
--);
--
--CREATE SEQUENCE seq_usuario
-- START WITH     1
-- INCREMENT BY   1
-- NOCACHE
-- NOCYCLE;

CREATE TABLE CARGO (
    ID_CARGO NUMBER NOT NULL,
    NOME varchar2(512) UNIQUE NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    PRIMARY KEY(ID_CARGO),
    CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE SEQUENCE seq_cargo
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
  
INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_ADMIN'); -- 1

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_AUXILIAR'); -- 2

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_CLIENTE'); -- 3

--CREATE TABLE FUNCIONARIO_CARGO (
--    ID_FUNCIONARIO NUMBER NOT NULL,
--    ID_CARGO NUMBER NOT NULL,
--    PRIMARY KEY(ID_FUNCIONARIO, ID_CARGO),
--    CONSTRAINT FK_FUNCIONARIO_CARGO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO),
--  	CONSTRAINT FK_FUNCIONARIO_CARGO_USUARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES USUARIO (ID_FUNCIONARIO)
);


--insert into usuario (id_funcionario, login, senha)
--     values (seq_usuario.nextval, 'maicon', '$2a$10$X.AxPaR2usWOKRyUT2ZX/.k5sdTQNkSUly3AlSibvxImFrNb9ulAu'); --1
--
--insert into usuario (id_funcionario, login, senha)
--     values (seq_usuario.nextval, 'admin', '$2a$10$X.AxPaR2usWOKRyUT2ZX/.k5sdTQNkSUly3AlSibvxImFrNb9ulAu'); --2
--	 
--insert into usuario (id_funcionario, login, senha)
--     values (seq_usuario.nextval, 'user', '$2a$10$X.AxPaR2usWOKRyUT2ZX/.k5sdTQNkSUly3AlSibvxImFrNb9ulAu'); --3
--
--insert into usuario (id_funcionario, login, senha)
--     values (seq_usuario.nextval, 'marketing', '$2a$10$X.AxPaR2usWOKRyUT2ZX/.k5sdTQNkSUly3AlSibvxImFrNb9ulAu'); --4
     
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (1,1); --MAICON / ADMIN
--
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (1,2); --MAICON / USER
--
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (1,3); --MAICON / MARKETING
--
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (2,1); --ADMIN / ADMIN
--
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (2,2); --ADMIN / USER
--
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (2,3); --ADMIN / MARKETING
--
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (3,2); --USER / USUARIO
--
--INSERT INTO FUNCIONARIO_CARGO (ID_FUNCIONARIO, ID_CARGO)
--VALUES (4,3); --MARKETING / MARKETING
--

